### ISSUE TITLE
Selecting a port number doesn't work

### ISSUE THREAD

**Issue by bh-e** [folkertvanheusden/HTTPing#11]
Hi, I am pasting a bug report received at Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922432
I also tested in v2.9. And I have the same result.

httping's manual says:

=====
       -p portnumber
              -p can be used together with -h. -p selects  the  portnumber  to
              probe.
=====

But it doesn't seem to be working:

=====
$ httping -p 443 josm.openstreetmap.de
PING josm.openstreetmap.de:80 (/):
connected to 95.216.72.248:80 (253 bytes), seq=0 time=522,23 ms
=====

See that it's still using port 80

"httping --help" also says:
Hi, I am pasting a bug report received at debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922432
I also tested in v2.9.

=====
-p x / --port            portnumber (e.g. 80) - use with -h
=====

But testing with -h I don't see any difference:

=====
$ httping -p 443 -h josm.openstreetmap.de
PING josm.openstreetmap.de:80 (/):
connected to 95.216.72.248:80 (253 bytes), seq=0 time=533,90 ms
=====

So either I did completely misunderstand the portnumber option or it's
really not working as expected.

**Comment by folkertvanheusden** [comment]
Hi,

Indeed it looks broken. Should be fixed now (commit f493d1e0d591c9fa702f930f6840ff6c004e536e).
