### ISSUE TITLE
AIX 404

### ISSUE THREAD

**Issue by OlafvdSpek** [folkertvanheusden/HTTPing#14]
Hoi Folkert,

De AIX page lijkt down en de releases zijn niet meer helemaal up-to-date: https://www.vanheusden.com/httping/

Groet

**Comment by folkertvanheusden** [comment]
Indeed!
The AIX packages are too old (AIX 5.3) so I removed them.

**Comment by OlafvdSpek** [comment]
The Changes list is still missing some updates.
