### ISSUE TITLE
Response Headers not refreshed

### ISSUE THREAD

**Issue by dylan-shipwell** [folkertvanheusden/HTTPing#20]
hey there, great tool, I noticed that if i start a session `httping example.org -K` and make a backend change, any changed headers are not shown in httping.

I thought this felt like a bug so I am letting you know. I would like to observe changes in headers while using httping as there are circumstances where i can gather details about the data-path between the client and the server based on the headers presented. A common example is some major cloud compute providers who add a vendor header can indicate that this request was served by a specific product, which can be nice to know if i'm trying to identify if requests are being served by that different backend yet or not.

Cheers!

**Comment by folkertvanheusden** [comment]
It was as-designed but I agree that it would be helpful to update it.
So I made a change for that.
It is on github in revision 09f89a993a4c2e7ae0ea2204c2c3b947ce332725

**Comment by dylan-shipwell** [comment]
Thank you! 

As designed, is there a notion that ncurses drawing may slow down the stats collection?

I have already run into many headers getting cut off, I haven't yet learned if there is a way to see that detail, but sometimes I make the font very small and that helps show more. 

Cheers!
