### ISSUE TITLE
short read during receiving reply-headers from host

### ISSUE THREAD

**Issue by O-ring** [folkertvanheusden/HTTPing#25]
Hello everyone,

I have compiled the current version (last commit november 16) on Slackware linux 15 (64 bit) and a regression was introduced: now I get this message when I run the following command:

httping -k https://www.google.com
Auto enabling SSL due to https-URL
PING www.google.com:443 (/):
short read during receiving reply-headers from host
short read during receiving reply-headers from host
short read during receiving reply-headers from host
short read during receiving reply-headers from host

Instead, I get the expected result with the version I downloaded on november 4:

httping  -k https://www.google.com
Auto enabling SSL due to https-URL
PING www.google.com:443 (/):
connected to 216.58.204.228:443 (1183 bytes), seq=0 time=181.59 ms 
connected to 216.58.204.228:443 (1362 bytes), seq=1 time=172.19 ms 
connected to 216.58.204.228:443 (1756 bytes), seq=2 time=165.77 ms 
connected to 216.58.204.228:443 (1756 bytes), seq=3 time=181.20 ms 

Any response is welcome.
Thanks in advance.

Cheers,
Marco

**Comment by folkertvanheusden** [comment]
Something goes wrong yes. When I compile it in a "git bisect" it works though?!
Am looking into it.

**Comment by folkertvanheusden** [comment]
I believe it is now fixed in 10dd32eff66955a6479a56bfbbd172f2cc7bc24c

**Comment by O-ring** [comment]
I tested it: it works now.
Thanks for your quick response.

Marco
