### ISSUE TITLE
Unknown type: useconds_t building on macOS

### ISSUE THREAD

**Issue by iandol** [folkertvanheusden/HTTPing#4]
_caveat emptor:_ I am not a c programmer...

Hi, when trying to update the formula for homebrew to build on macOS, I hit this error:

```
In file included from nc.c:22:
./utils.h:19:15: error: unknown type name 'useconds_t'
void myusleep(useconds_t v);
```

 I see `#include <unistd.h>` is present in `utils.c` and I'm sure this is in the compiler path somehow (the developer tools on macOS includes the standard SDK and libc AFAIK). Reading this man page:

https://man7.org/linux/man-pages/man3/usleep.3.html

It suggested to replace `useconds_t` with `unsigned int`, and doing that in `utils.h` and httping compiles without any further issues. For homebrew I can automaticallt replace this before making, but just wanted to flag this.

**Comment by folkertvanheusden** [comment]
Thank you.
If you can automatically replace it that would be great.
