### ISSUE TITLE
Add a tagged release

### ISSUE THREAD

**Issue by iandol** [folkertvanheusden/HTTPing#6]
For package systems like homebrew, having a release which has been tagged with a version means the download is more reliable (as I understand it the SHA256 will remain consistent, whereas the master branch download will change for every commit). 

This has been requested by the package maintainers at homebrew, you can follow my attempt to add httping back here:

https://github.com/Homebrew/homebrew-core/pull/114088

**Comment by folkertvanheusden** [comment]
Hi,

https://github.com/folkertvanheusden/HTTPing/releases/tag/v2.9

Will this work?

regards

p.s. thanks for your help

**Comment by iandol** [comment]
Yes, this is perfect thanks! We have one more outstanding issue then I think httping will be available again in the homebrew packages...
