### ISSUE TITLE
secure sites failing

### ISSUE THREAD

**Issue by DLewis01** [folkertvanheusden/HTTPing#9]
when running with httping -K  https://[SITE]

19.60.108:443 (1020 bytes), seq=0 time=212.90 ms 200 OKSSL certificate validation failed unable to get local issuer certificate

This appears for all sites I've tested.
i.e. 
httping -K https://www.news.com.au
httping -K https://www.abc.net.au

**Comment by folkertvanheusden** [comment]
cannot reproduce

**Comment by DLewis01** [comment]
<img width="997" alt="Screen Shot 2023-08-28 at 5 08 47 pm" src="https://github.com/folkertvanheusden/HTTPing/assets/20555197/bf7f3474-48d6-42f7-8488-a5499ed799fe">
<img width="1002" alt="Screen Shot 2023-08-28 at 5 08 30 pm" src="https://github.com/folkertvanheusden/HTTPing/assets/20555197/89f31259-22a4-45f8-b021-5d3b72428568">

**Comment by folkertvanheusden** [comment]
![image](https://github.com/folkertvanheusden/HTTPing/assets/85709915/a6dd5528-196c-4dbf-b519-264e47a722cc)

Maybe your system clock is off? Or certificates not installed? I don't know!

**Comment by zffocussss** [comment]
I have this issues on my Mac Pro.
<img width="767" alt="image" src="https://github.com/folkertvanheusden/HTTPing/assets/46145695/774d92c8-ad14-4687-80cc-7ea3871a7f39">
